name: AWS Secrets Manager integration test
on:
  pull_request:
    branches:
      - master


jobs:
  run-integrationtest:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.4

      # Setup aws credential
    - name: run aws scm integration test
      run: |
        export AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}
        export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
        export AWS_REGION=${{secrets.AWS_REGION}}
        go test -v aws/aws_secrets_manager/aws_scm_integration_test.go aws/aws_secrets_manager/aws_scm.go aws/aws_secrets_manager/aws_secret_store_integration_test.go
